### ISSUE TITLE
junos_install_os fires an error on reboot of EX with 16.1R1.11

### ISSUE THREAD

**Issue by renetbo** [Juniper/ansible-junos-stdlib#178] opened 2016-11-16 15:39 UTC
Hi,

There is an error raised at the reboot when using it with EX92K 16.1R1.11. The workaround it to enable the no_reboot and then run a new task that runs the cli request system reboot.

Thanks

B

**Comment by stacywsmith** [comment] 2016-11-16 17:03
Are you connecting to the EX92K over a console connection, or using NETCONF over SSH?

Can you provide details on the specific error you are seeing?

**Comment by renetbo** [comment] 2016-11-28 13:32
I am connected via console. Here is what happens (EX9200-T1 is mono RE, T2 is dual RE):
ok: [EX9200-T2] => {"changed": false, "check_mode": false, "invocation": {"module_args": {"host": "EX9200-T2", "logfile": "/var/tmp/build/EX9200-T2/ansible-run.log", "no_copy": false, "package": "/var/tmp/junos/junos-install-ex92xx-x86-64-16.1R1-S2.tgz", "passwd": "Password1", "port": 830, "reboot": true, "reboot_pause": 1, "user": "root", "version": "16.1R1-S2"}, "module_name": "junos_install_os"}, "ver": {"has": "16.1R1-S2", "should": "16.1R1-S2"}}
fatal: [EX9200-T1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "junos_install_os"}, "module_stderr": "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py:533: RuntimeWarning: An unknown exception occured - please report.\n  RuntimeWarning)\nTraceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1480339494.54-8839755935450/junos_install_os\", line 2248, in <module>\n    main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1480339494.54-8839755935450/junos_install_os\", line 253, in main\n    results = junos_install_os(module, dev)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1480339494.54-8839755935450/junos_install_os\", line 203, in junos_install_os\n    rsp = sw.reboot()\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 533, in reboot\n    if err.rsp.findtext('.//error-severity') != 'warning':\nAttributeError: 'XMLSyntaxError' object has no attribute 'rsp'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by stacywsmith** [comment] 2016-11-30 03:22
I believe this is a Junos issue where the device begins to reboot before the complete NETCONF XML response has been written to the device console. Therefore, PyEZ/Ansible reports the XML syntax error. Until this issue can be addressed in Junos, I recommend using junos_install_os via the normal NETCONF over SSH channel rather than over a console connection.

Alternatively, you can continue to use the workaround you mention in your initial report of this issue.

**Comment by renetbo** [comment] 2016-11-30 09:43
Sorry I made an error in my previous message, I am connected via ssh not console when the problem happens.

B

**Comment by stacywsmith** [comment] 2016-11-30 16:30
@renetbo In that case, could you please enable NETCONF traceoptions on EX9200-T1 and recreate your failure? Please share the content of the resulting `/var/log/netconf.log` traceoptions file.
```
set system services netconf traceoptions flag all
set system services netconf traceoptions file netconf.log
```

**Comment by renetbo** [comment] 2016-11-30 17:31
Here it is 
[netconf.txt](https://github.com/Juniper/ansible-junos-stdlib/files/622532/netconf.txt)

**Comment by stacywsmith** [comment] 2016-11-30 19:46
@renetbo Thanks for providing the NETCONF traceoptions. The problem is actually in the last few lines of the file in the response to the `<request-reboot>` RPC.
```
Nov 30 17:27:01 [NETCONF] - [5297] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:9f5ca7e7-a2e2-4643-a1a5-25a6de919f68"><request-reboot><in>0</in></request-reboot></nc:rpc>]]>]]>
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.1R1/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:9f5ca7e7-a2e2-4643-a1a5-25a6de919f68">
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: <request-reboot-results>
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: <request-reboot-status reboot-time>
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: Shutdown NOW!
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: [pid 13069]
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: </request-reboot-status>
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: </request-reboot-results>
Nov 30 17:27:01 [NETCONF] - [5297] Outgoing: </rpc-reply>
```

In this response, the `<request-reboot-status reboot-time>` XML tag has a malformed XML attribute. All XML attributes must be in the form `name="value"`, but in this case the `reboot-time` attribute only has a `name` and no `="value"`. The XML tag should look like this instead: `<request-reboot-status reboot-time="1471942144">`

This is actually a known Junos bug in the version that is running on the device prior to the upgrade (16.1R.11 in this case.)

This bug is present on MX platforms (including the EX-92xx) in all 15.1 releases and in 16.1R1 and 16.1R2 releases. The bug is fixed in Junos releases >= 16.1R3.

If the device is running a version affected by this bug, you'll have to use the workaround described in your original post.

**Closed by stacywsmith** 2016-11-30 19:46 UTC

**Comment by renetbo** [comment] 2016-11-30 21:29
Thanks for the details Stacy so I will stick with the workaround then. Any reasons why the EX9200 with dual RE does not exhibit the problem?

**Comment by stacywsmith** [comment] 2016-11-30 21:35
> Any reasons why the EX9200 with dual RE does not exhibit the problem?

In the log you included, it didn't exhibit the problem because it wasn't actually upgraded, and therefore it wasn't rebooted. Here's the snippet from your log in this thread:
```
ok: [EX9200-T2] => {"changed": false, "check_mode": false, "invocation": {"module_args": {"host": "EX9200-T2", "logfile": "/var/tmp/build/EX9200-T2/ansible-run.log", "no_copy": false, "package": "/var/tmp/junos/junos-install-ex92xx-x86-64-16.1R1-S2.tgz", "passwd": "Password1", "port": 830, "reboot": true, "reboot_pause": 1, "user": "root", "version": "16.1R1-S2"}, "module_name": "junos_install_os"}, "ver": {"has": "16.1R1-S2", "should": "16.1R1-S2"}}
```
Notice that the `has` and `should` versions are both `16.1R1-S2`. If the device is already running the correct version, the upgrade is not performed. That appears to be the case for EX9200-T2.

**Comment by renetbo** [comment] 2016-11-30 21:37
That explains it indeed :)
