### ISSUE TITLE
Unable to close the configuration: UnlockError

### ISSUE THREAD

**Issue by holynakamoto** [Juniper/ansible-junos-stdlib#578] opened 2021-11-23 18:59 UTC
```
- name: "Get committed configuration"
  juniper.device.config:
    timeout: 120
    retrieve: "committed"
    format: "set"
    dest_dir: "{{ playbook_dir }}/roles/junos_config/files/configs/set"
  register: response
```
Unable to close the configuration: UnlockError'
```
<rpc>
    <unlock-configuration/>
</rpc><rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos">
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
Configuration database is not open
</error-message>
</rpc-error>
<rpc>
    <open-configuration>
        <private/>
    </open-configuration>
</rpc></rpc-reply>
]]>]]>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos">
<rpc>
    <unlock-configuration/>
</rpc></rpc-reply>
]]>]]>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos">
<rpc>
    <close-session/>
</rpc></rpc-reply>
]]>]]>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/20.2R0/junos">
<ok/>

</rpc-reply>
]]>]]>
<!-- session end at 2021-11-23 18:32:04 UTC -->
```

I'm running this playbook against my entire inventory only this one device is produces the error.

```
Model: ex4300-48t
Junos: 20.2R3.9
JUNOS EX  Software Suite [20.2R3.9]
JUNOS FIPS mode utilities [20.2R3.9]
JUNOS Crypto Software Suite [20.2R3.9]
JUNOS Online Documentation [20.2R3.9]
JUNOS Phone-Home Software Suite [20.2R3.9]
JUNOS jsd [powerpc-20.2R3.9-jet-1]
JUNOS SDN Software Suite [20.2R3.9]
JUNOS EX 4300 Software Suite [20.2R3.9]
JUNOS Web Management Platform Package [20.2R3.9]
JUNOS py-base-powerpc [20.2R3.9]
JUNOS py-base2-powerpc [20.2R3.9]
JUNOS py-extensions-powerpc [20.2R3.9]
JUNOS py-extensions2-powerpc [20.2R3.9]
REST API Software Suite [20.2R3.9]
```

**Comment by holynakamoto** [comment] 2021-11-24 17:31
@rahkumar651991 any idea here?

**Comment by michaelmcdonald** [comment] 2022-02-15 15:33
Few months late, but I rate into the same issue. My problem was I was attempting to run my playbook against a device that was configured to be a `line-card` role in a virtual-chassis. Ran it against the master and it worked.

**Comment by holynakamoto** [comment] 2022-02-15 17:29
@michaelmcdonald thanks for that, looks like it's not the case here.

**Comment by holynakamoto** [comment] 2022-02-15 17:29
`nmoore@SFO-651-1.2> show virtual-chassis status

Virtual Chassis ID: 211f.5f43.74f6
Virtual Chassis Mode: Enabled
                                                Mstr           Mixed Route Neighbor List
Member ID  Status   Serial No    Model          prio  Role      Mode  Mode ID  Interface
0 (FPC 0)  Prsnt    PD3718270236 ex4300-48p     128   Master*      N  VC`

**Comment by dineshbaburam91** [comment] 2022-07-26 09:55
@holynakamoto Kindly confirm MGD process is up and running in the device. This could be some device issue where the MGD database got corrupted or MGD is busy committing other configurations.

**Comment by michaelmcdonald** [comment] 2023-06-28 13:24
@holynakamoto: I'm running into this error again; however it's a single switch and not a VC stack. Did you ever discover the cause of your problem?

**Comment by apurvaraghu** [comment] 2024-02-06 18:59
Is this issue seen only on a particular device? Can you confirm what device you are using here?

**Comment by apurvaraghu** [comment] 2024-02-07 19:02
The error is usually due to other users using the device and the system can't release the lock for you. Please check if you still run into this error when no users are using the same device. I tried to replicate this using the same playbook as above on a Junos device and I can see that the configuration is retrieved successfully. 

<img width="297" alt="Screenshot 2024-02-07 at 10 57 18 AM" src="https://github.com/Juniper/ansible-junos-stdlib/assets/100869315/d65dac93-b4e8-402d-b2fe-087d03c3461a">

  
<img width="1157" alt="Screenshot 2024-02-07 at 10 57 59 AM" src="https://github.com/Juniper/ansible-junos-stdlib/assets/100869315/b89c9448-5621-47e4-96ad-60271874f23b">
<img width="1207" alt="Screenshot 2024-02-07 at 10 47 09 AM" src="https://github.com/Juniper/ansible-junos-stdlib/assets/100869315/67c97133-94db-4020-a505-f3f264c55463">

**Comment by apurvaraghu** [comment] 2024-02-08 04:08
A configuration lock error can occur for the following reasons:
•	Another user has an exclusive lock on the configuration.
•	Another user made changes to the shared configuration database but has not yet committed the changes.
•	The user executing the Junos PyEZ code does not have permissions to configure the device.
https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/task/junos-pyez-configuration-errors-troubleshooting.html

Kindly check if your error is not due to the above reasons.

**Comment by dineshbaburam91** [comment] 2024-05-07 06:54
The issue will be closed after documenting and updating the solutions in the ticket. If the issue persists, please feel free to reopen the ticket.


https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/task/junos-pyez-configuration-errors-troubleshooting.html

**Closed by dineshbaburam91** 2024-05-07 06:54 UTC
Labels: need-info, Type: Bug
