### ISSUE TITLE
Improvement: In console junos_install_config stuck if user already in conf mode

### ISSUE THREAD

**Issue by renetbo** [Juniper/ansible-junos-stdlib#180] opened 2016-11-18 09:25 UTC
Hi all,

What I've noticed is that if a user is already in config mode (while the config has not been modified) then frees up the console of the equipment, if we launch the junos_install_config via console, there is a "login_warn:shell login was open!" in the debug and the process is stuck there (i.e. config is never pushed) until it times out.
It would be better to have a warning and stop Ansible so that the user can fix it instead of waiting for the timeout (which is several minutes)

This problem is not seen in ssh mode.

Rgds

B

**Comment by renetbo** [comment] 2016-11-23 10:48
In fact this login_warn is coming from /usr/local/lib/python2.7/dist-packages/netconify/tty.py

Do you think it would be possible to modify tty.py to triggers an error instead of a warning as Ansible could react to it instead of being stuck?

**Comment by stacywsmith** [comment] 2017-11-06 23:38
@renetbo Netconify is no longer used by the Ansible modules for console connectivity. Instead, the equivalent functionality is now provided by PyEZ.

Please retest this with the latest module code from GitHub. If the issue is still seen, it will need to be fixed via a PyEZ issue.

**Closed by stacywsmith** 2017-11-06 23:38 UTC
