### ISSUE TITLE
Keys returned on config_parsed by juniper_junos_config use invalid characters 

### ISSUE THREAD

**Issue by ustrum** [Juniper/ansible-junos-stdlib#422] opened 2019-03-27 08:55 UTC
Issue Type
------

 - Bug Report

Module Name
------

juniper_junos_config

Juniper.Junos role and Python libraries version

```
[vagrant@srv1 test]$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ansible==2.7.9
Babel==0.9.6
backports.ssl-match-hostname==3.5.0.1
cffi==1.6.0
chardet==2.2.1
configobj==4.7.2
cryptography==1.7.2
decorator==3.4.0
enum34==1.0.4
httplib2==0.9.2
idna==2.4
iniparse==0.4
ipaddress==1.0.16
Jinja2==2.7.2
jmespath==0.9.0
junos-eznc==2.2.0
jxmlease==1.0.1
kitchen==1.1.1
lxml==4.3.2
MarkupSafe==0.11
ncclient==0.6.3
netaddr==0.7.19
paramiko==2.1.1
passlib==1.6.5
perf==0.1
ply==3.4
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyserial==3.4
python-keyczar==0.71rc0
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
schedutils==0.4
scp==0.13.2
selectors2==2.0.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
urlgrabber==3.10
yum-metadata-parser==1.1.4
[vagrant@srv1 test]$ ansible-galaxy list
 [WARNING]: - the configured path /home/vagrant/.ansible/roles does not exist.

 [WARNING]: - the configured path /usr/share/ansible/roles does not exist.

- Juniper.junos, 2.1.0

```

OS / Environment
------
CentOS 7

I am using a vagrant vqfx on JUNOS 15.1X53-D60.4, but also tested on several SRX clusters running junos v15

Summary
------

The keys used in the json returned by juniper_junos_config on the config_parsed variable use an invalid character sometimes ("-") which makes it imposible to reference and access the value of those entries later on.

Since the documentation specifies this value is a json datastructure, it is not a valid yaml since it uses keys containing invalid characters. 

Steps to reproduce
------

```yaml
---
- name: "Check if line is present in device config."
  hosts: vqfx1
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: "Get snmp config and save to response var"
      juniper_junos_config:
        user: "vagrant"
        host: "{{ ansible_host }}"
        retrieve: "committed"
        format: "xml"
        filter: "snmp"
      register: response

    - name: "Debug response var"
      debug:
        var: response

    - name: "Try to access snmp name through config_parsed"
      debug:
        var: response.config_parsed.configuration.snmp.system-name
      when: "response.config_parsed.configuration.snmp.system-name is defined"

```

I used a vqfx with only this line in the snmp hierarchy:

vagrant@vqfx1> show configuration snmp | display set
set snmp name vqfx1

{master:0}
vagrant@vqfx1>

Expected results

```
For the first two tasks in the playbook, notice the "_" instead of the "-" in the config_parsed key:

[vagrant@srv1 test]$ ansible-playbook -i inventory test.yml

PLAY [Check if line is present in device config.] **********************************************************************************************************************************

TASK [Get snmp config and save to response var] ************************************************************************************************************************************
ok: [vqfx1]

TASK [Debug response var] **********************************************************************************************************************************************************
ok: [vqfx1] => {
    "response": {
        "changed": false,
        "config": "<configuration commit-seconds=\"1553675472\" commit-localtime=\"2019-03-27 08:31:12 UTC\" commit-user=\"vagrant\">\n    <snmp>\n        <system-name>vqfx1</system-name>\n    </snmp>\n</configuration>\n\n",
        "config_lines": [
            "<configuration commit-seconds=\"1553675472\" commit-localtime=\"2019-03-27 08:31:12 UTC\" commit-user=\"vagrant\">",
            "    <snmp>",
            "        <system-name>vqfx1</system-name>",
            "    </snmp>",
            "</configuration>",
            ""
        ],
        "config_parsed": {
            "configuration": {
                "snmp": {
                    "system_name": "vqfx1"
                }
            }
        },
        "failed": false,
        "msg": "Configuration has been: opened, retrieved, closed."
    }
}


PLAY RECAP *************************************************************************************************************************************************************************
vqfx1                      : ok=2    changed=0    unreachable=0    failed=0

```
Actual results
------

```
[vagrant@srv1 test]$ ansible-playbook -i inventory test.yml

PLAY [Check if line is present in device config.] **********************************************************************************************************************************

TASK [Get snmp config and save to response var] ************************************************************************************************************************************
ok: [vqfx1]

TASK [Debug response var] **********************************************************************************************************************************************************
ok: [vqfx1] => {
    "response": {
        "changed": false,
        "config": "<configuration commit-seconds=\"1553675472\" commit-localtime=\"2019-03-27 08:31:12 UTC\" commit-user=\"vagrant\">\n    <snmp>\n        <system-name>vqfx1</system-name>\n    </snmp>\n</configuration>\n\n",
        "config_lines": [
            "<configuration commit-seconds=\"1553675472\" commit-localtime=\"2019-03-27 08:31:12 UTC\" commit-user=\"vagrant\">",
            "    <snmp>",
            "        <system-name>vqfx1</system-name>",
            "    </snmp>",
            "</configuration>",
            ""
        ],
        "config_parsed": {
            "configuration": {
                "snmp": {
                    "system-name": "vqfx1"
                }
            }
        },
        "failed": false,
        "msg": "Configuration has been: opened, retrieved, closed."
    }
}

TASK [Try to access snmp name through config_parsed] *******************************************************************************************************************************
fatal: [vqfx1]: FAILED! => {"msg": "The conditional check 'response.config_parsed.configuration.snmp.system-name is defined' failed. The error was: error while evaluating conditional (response.config_parsed.configuration.snmp.system-name is defined): Unable to look up a name or access an attribute in template string ({% if response.config_parsed.configuration.snmp.system-name is defined %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': unsupported operand type(s) for -: 'StrictUndefined' and 'bool'\n\nThe error appears to have been in '/home/vagrant/test/test.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"Try to access snmp name through config_parsed\"\n      ^ here\n"}
        to retry, use: --limit @/home/vagrant/test/test.retry

PLAY RECAP *************************************************************************************************************************************************************************
vqfx1                      : ok=2    changed=0    unreachable=0    failed=1

```

**Comment by stacywsmith** [comment] 2019-03-27 14:55
A `-` **is** a valid character in a JSON string and object name. Per [json.org](http://json.org/) a string can be comprised of "Any UNICODE character except `"` or `\` or control character".

A `-` is also a valid character in YAML.

The issue is that Python does not allow a `-` in a variable name, and Ansible allows accessing a nested dict using the dot notation. When using this notation, each portion of the data structure must be a valid Python variable name. Therefore, when one of the keys in the nested data structure isn't a valid Python variable name, you can't use the dot notation. However, you can still access the content using the normal square-bracket notation.

Specifically, you have:
```
    - name: "Try to access snmp name through config_parsed"
      debug:
        var: response.config_parsed.configuration.snmp.system-name
      when: "response.config_parsed.configuration.snmp.system-name is defined"
```

Try this instead:
```
    - name: "Try to access snmp name through config_parsed"
      debug:
        var: response.config_parsed.configuration.snmp['system-name']
      when: "response.config_parsed.configuration.snmp['system-name'] is defined"
```

or alternatively:
```
    - name: "Try to access snmp name through config_parsed"
      debug:
        var: response['config_parsed']['configuration']['snmp']['system-name']
      when: "response['config_parsed']['configuration']['snmp']['system-name'] is defined"
```

**Comment by ustrum** [comment] 2019-03-28 17:37
Thanks for the clarification about json and yaml using "-" for string and object names. I found [a related issue in ansible ](https://github.com/ansible/ansible/issues/8849)and seems ansible doesn't accept "-" on the names of variables.

Assuming the return value is a json, I accept it is a valid json, but I find it a bit annoying having to stick to the dictionary notation and I guess it makes not a valid ansible variable regarding that link.

Thanks again.

**Comment by rsmekala** [comment] 2019-04-01 05:09
@stacywsmith Thanks for the detailed explanation.

@ustrum Closing this issue. Please do reopen if required.

**Closed by rsmekala** 2019-04-01 05:09 UTC
