### ISSUE TITLE
juniper_junos_config: Traceback when committing configuration.

### ISSUE THREAD

**Issue by gcasella** [Juniper/ansible-junos-stdlib#533] opened 2020-11-25 17:51 UTC
Issue Type
------
 - Bug Report

Module Name
------

juniper_junos_config

```
ansible 2.10.3
  config file = /Users/gianluca.casella/Documents/awx/ansible.cfg
  configured module search path = ['/Users/gianluca.casella/Documents/3.9venv/lib/python3.7/site-packages/ansible/modules']
  ansible python module location = /Users/gianluca.casella/Documents/3.9venv/lib/python3.9/site-packages/ansible
  executable location = /Users/gianluca.casella/Documents/3.9venv/bin/ansible
  python version = 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) [Clang 6.0 (clang-600.0.57)]

ansible==2.10.3
ansible-base==2.10.3
appdirs==1.4.4
asgiref==3.3.1
asn1crypto==1.4.0
attrs==20.3.0
bcrypt==3.2.0
beautifulsoup4==4.9.3
cached-property==1.5.2
certifi==2020.11.8
cffi==1.14.3
chardet==3.0.4
colorama==0.4.4
configparser==5.0.1
cryptography==3.2.1
defusedxml==0.6.0
et-xmlfile==1.0.1
future==0.18.2
icdiff==1.9.1
idna==2.10
isodate==0.6.0
jdcal==1.4.1
Jinja2==2.11.2
jsnapy==1.3.4
junos-eznc==2.5.4
jxmlease==1.0.3
ldap3==2.8.1
lxml==4.6.1
MarkupSafe==1.1.1
mysqlclient==2.0.1
ncclient==0.6.9
netaddr==0.8.0
numpy==1.19.4
openpyxl==3.0.5
packaging==20.4
pandas==1.1.4
paramiko==2.7.2
ping3==2.6.6
plotly==4.12.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pymssql==2.1.5
PyMySQL==0.10.1
PyNaCl==1.4.0
pyparsing==2.4.7
pyserial==3.4
python-dateutil==2.8.1
python-ldap==3.3.1
pytz==2020.4
PyYAML==5.3.1
requests==2.24.0
requests-file==1.5.1
requests-toolbelt==0.9.1
retrying==1.3.3
scp==0.13.3
simplejson==3.17.2
six==1.15.0
soupsieve==2.0.1
sqlparse==0.4.1
transitions==0.8.5
urllib3==1.25.11
yamlordereddictloader==0.4.0
zeep==4.0.0
```

OS / Environment
------

Juniper EX3200 v11.4R8.5
Summary
------

This is only related to the EX3200 devices (which I know are not supported by Juniper anymore. This problem does not appear on EX4300's)

I can fix this by setting the **diff: ** tag to **false**
Steps to reproduce
------

```yaml
---
- name: Playbook Run
  hosts:
    - all
  connection: netconf
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Wait for devices to become reachable. Will timeout after 30 Minutes.
      wait_for: host={{ ansible_host }} port=830 timeout=60
      register: reboot_status

    - name: Get JunOS Facts # already do this in the upload playbook
      juniper_junos_facts:
        provider: '{{ cli }}'
      register: junos

---
- name: Retrieve JunOS Loopback Interface Configuration(s)
  juniper_junos_config:
    provider: '{{ cli }}'
    retrieve: 'committed'
    filter: '<interfaces><interface><name>lo0</name></interface></interfaces>'
    format: 'xml'
  register: loopback_filter

- name: Commiting Removal of Loopback filter from lo0
  juniper_junos_config:
    provider: '{{ cli }}'
    config_mode: 'private'
    load: 'merge'
    format: 'set'
    comment: '# Remove Loopback filter from lo0'
    lines:
      - delete interfaces lo0 unit 0 family inet filter input {{ loopback_filter.config_parsed.configuration.interfaces.interface.unit.family.inet.filter.input['filter-name'] }}
  register: remove_loopback_filter
  when:
    - loopback_filter is defined
    - loopback_filter.config_parsed.configuration.interfaces.interface.unit.family.inet.filter is defined

- pause:
    seconds: 7

- name: Are devices still reachable?
  wait_for: host={{ ansible_host }} port=830 timeout=60
  register: reboot_status
  ignore_errors: True
```

Expected results

```
PLAY [Playbook Run] *******************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Wait for devices to become reachable. Will timeout after 30 Minutes.] ****************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR1]

TASK [Get JunOS Facts] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR1]

TASK [Retrieve JunOS Loopback Interface Configuration(s)] **********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR1]

TASK [Commiting Removal of Loopback filter from lo0] ***************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [RTR1]

TASK [pause] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Pausing for 7 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [RTR1]

TASK [Are devices still reachable?] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR1]

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
RTR1            : ok=8    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
Actual results
------

```
PLAY [Request System Snapshot Media] *******************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Wait for devices to become reachable. Will timeout after 30 Minutes.] ****************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR01]

TASK [Get JunOS Facts] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR01]

TASK [Retrieve JunOS Loopback Interface Configuration(s)] **********************************************************************************************************************************************************************************************************************************************************************************************************
ok: [RTR01]


TASK [Commiting Removal of Loopback filter from lo0] ***************************************************************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'text'
fatal: [RTR01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/gianluca.casella/.ansible/tmp/ansible-local-42030zz3xmum7/ansible-tmp-1606323109.5518222-42107-163672533664336/AnsiballZ_juniper_junos_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/gianluca.casella/.ansible/tmp/ansible-local-42030zz3xmum7/ansible-tmp-1606323109.5518222-42107-163672533664336/AnsiballZ_juniper_junos_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/gianluca.casella/.ansible/tmp/ansible-local-42030zz3xmum7/ansible-tmp-1606323109.5518222-42107-163672533664336/AnsiballZ_juniper_junos_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.juniper_junos_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_kk6zr1yo/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/modules/juniper_junos_config.py\", line 1140, in <module>\n  File \"/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_kk6zr1yo/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/modules/juniper_junos_config.py\", line 1072, in main\n  File \"/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_kk6zr1yo/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 1582, in diff_configuration\n  File \"/Users/gianluca.casella/Documents/Work/WNCE/gitlab.int.bell.ca/3.9venv/lib/python3.9/site-packages/jnpr/junos/utils/config.py\", line 263, in diff\n    diff_txt = rsp.find(\"configuration-output\").text\nAttributeError: 'NoneType' object has no attribute 'text'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
RTR01            : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
Traceback with -vvv
```
The full traceback is:
Traceback (most recent call last):
  File "/Users/gianluca.casella/.ansible/tmp/ansible-local-42136nx0s9_ut/ansible-tmp-1606323153.641433-42227-3825941385090/AnsiballZ_juniper_junos_config.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/gianluca.casella/.ansible/tmp/ansible-local-42136nx0s9_ut/ansible-tmp-1606323153.641433-42227-3825941385090/AnsiballZ_juniper_junos_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/gianluca.casella/.ansible/tmp/ansible-local-42136nx0s9_ut/ansible-tmp-1606323153.641433-42227-3825941385090/AnsiballZ_juniper_junos_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.juniper_junos_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_0ccz6tum/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/modules/juniper_junos_config.py", line 1140, in <module>
  File "/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_0ccz6tum/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/modules/juniper_junos_config.py", line 1072, in main
  File "/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_0ccz6tum/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 1582, in diff_configuration
  File "/Users/gianluca.casella/Documents/Work/WNCE/gitlab.int.bell.ca/3.9venv/lib/python3.9/site-packages/jnpr/junos/utils/config.py", line 263, in diff
    diff_txt = rsp.find("configuration-output").text
AttributeError: 'NoneType' object has no attribute 'text'
fatal: [BMCL-W5235-MCE1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/gianluca.casella/.ansible/tmp/ansible-local-42136nx0s9_ut/ansible-tmp-1606323153.641433-42227-3825941385090/AnsiballZ_juniper_junos_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/gianluca.casella/.ansible/tmp/ansible-local-42136nx0s9_ut/ansible-tmp-1606323153.641433-42227-3825941385090/AnsiballZ_juniper_junos_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/gianluca.casella/.ansible/tmp/ansible-local-42136nx0s9_ut/ansible-tmp-1606323153.641433-42227-3825941385090/AnsiballZ_juniper_junos_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.juniper_junos_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_0ccz6tum/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/modules/juniper_junos_config.py\", line 1140, in <module>\n  File \"/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_0ccz6tum/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/modules/juniper_junos_config.py\", line 1072, in main\n  File \"/var/folders/bs/7tvs228d6vz_29sz_25t6pxm0000gn/T/ansible_juniper_junos_config_payload_0ccz6tum/ansible_juniper_junos_config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 1582, in diff_configuration\n  File \"/Users/gianluca.casella/Documents/Work/WNCE/gitlab.int.bell.ca/3.9venv/lib/python3.9/site-packages/jnpr/junos/utils/config.py\", line 263, in diff\n    diff_txt = rsp.find(\"configuration-output\").text\nAttributeError: 'NoneType' object has no attribute 'text'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by rahkumar651991** [comment] 2021-10-12 04:54
Hi @gcasella, 
As mentioned the issue is specific to the device. On the newer version of junos, this should work fine. We recommend to use diff as false for this scenario.
Closing this issue as this is device specific.

**Closed by rahkumar651991** 2021-10-12 04:54 UTC
