### ISSUE TITLE
junos_install_config ran into RPC connection close error

### ISSUE THREAD

**Issue by henrchen** [Juniper/ansible-junos-stdlib#216] opened 2017-03-15 18:15 UTC
Once in a while we ran into this problem. Ansible playbook run shows RPC connection close error and switch's syslog has "missing rpc tag" (or something like that).

We can scp the config template to a switch and do a "load override" without any problem. Sometimes removing an extra tab or whitespaces could help. But not always. I can isolate the issue to certain sections in a config template. If I take this section out, it works. When I compare the same section in this erroneous template and a working template (for another switch or different version of the template where changes were made in a different section), I could not find any difference visually or in MD5 checksum.  

I also tested this with Ansible's "junos_config" function and I could not reproduce this problem.

I do not have a solid method to reproduce this problem. It can occur on different switches or same switches at different time.

**Comment by nitzan-tz** [comment] 2017-05-08 18:09
I have the same issue with one switch once every few times it return an error when commuting the configuration.
On the switch I get 
`UI_NETCONF_ERROR: NETCONF error: syntax error, expecting <rpc>`

And on the server I get 
`fatal: [switch1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/tmp/ansible_a6g_5u/ansible_module_junos_install_config.py:198: SyntaxWarning: import * only allowed at module level\n  def _load_via_netconf(module):\nTraceback (most recent call last):\n  File \"/tmp/ansible_a6g_5u/ansible_module_junos_install_config.py\", line 454, in <module>\n    main()\n  File \"/tmp/ansible_a6g_5u/ansible_module_junos_install_config.py\", line 451, in main\n    _ldr(module)\n  File \"/tmp/ansible_a6g_5u/ansible_module_junos_install_config.py\", line 289, in _load_via_netconf\n    diff = cu.diff()\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py\", line 196, in diff\n    compare='rollback', rollback=str(rb_id), format='text'\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py\", line 156, in _exec_rpc\n    return self._junos.execute(rpc, **dec_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 71, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 26, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py\", line 522, in execute\n    raise EzErrors.ConnectClosedError(self)\njnpr.junos.exception.ConnectClosedError: ConnectClosedError(10.1.1.1)\n", "module_stdout": "", "msg": "MODULE FAILURE"}`

Nitzan

**Comment by stacywsmith** [comment] 2017-05-08 18:52
@henrchen @nitzan-tz 

Can you each try and reproduce this problem with NETCONF traceoptions configured?
```
set system services netconf traceoptions flag all
set system services netconf traceoptions file netconf.log
```

Once reproduced, please provide the full netconf.log of the entire session where it was reproduced. You can either post the NETCONF traceoptions log back to this thread or email directly to me at stacys at juniper dot net.

You can also send me details on your platform and Junos software version.

FWIW, I believe your likely seeing the same thing as: https://github.com/ncclient/ncclient/issues/189#issuecomment-298469541

However, the NETCONF traceoptions file will let me say definitively.

**Comment by nitzan-tz** [comment] 2017-05-09 06:26
The switch is QFX5100 running 14.1X53-D40.8
The wired thing is that its hard to reproduce the issue with the same
configuration it happen once every few times and only when pushing
configuration to the whole data center
I wasn't able to reproduce it when I push configuration only to that switch
with --limit

I will try to catch it with traceoptions

Nitzan

**Comment by stacywsmith** [comment] 2017-05-09 14:46
@nitzan-tz 
It doesn't surprise me that this is hard to reproduce. The issue I am suspecting only occurs when the full size of the NETCONF RPC being sent to the device falls within a 5 byte window. Changes to the size of the payload (the config file) OR to the actual RPC will effect whether or not the total RPC size falls within this window.

The 14.1X53-D40.8 version of Junos is susceptible to the issue I am suspecting. The issue is fixed in releases >= 16.1R1.

If you are able to catch it with traceoptions, I can confirm whether or not it actually is this issue.

**Comment by cvicente** [comment] 2017-06-07 19:46
I am hitting this same problem. Here's the Ansible output:
```
TASK [Deploy configuration] ****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jnpr.junos.exception.ConnectClosedError: ConnectClosedError(host.example.net)
fatal: [host.example.net]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/cvicente/.ansible/tmp/ansible-tmp-1496862538.56-92915643699810/junos_install_config\", line 2467, in <module>\n    main()\n  File \"/Users/cvicente/.ansible/tmp/ansible-tmp-1496862538.56-92915643699810/junos_install_config\", line 480, in main\n    _ldr(module)\n  File \"/Users/cvicente/.ansible/tmp/ansible-tmp-1496862538.56-92915643699810/junos_install_config\", line 316, in _load_via_netconf\n    diff = cu.diff()\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/utils/config.py\", line 229, in diff\n    compare='rollback', rollback=str(rb_id), format='text'\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py\", line 336, in _exec_rpc\n    return self._junos.execute(rpc, **dec_args)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/decorators.py\", line 76, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/decorators.py\", line 31, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/device.py\", line 718, in execute\n    raise EzErrors.ConnectClosedError(self)\njnpr.junos.exception.ConnectClosedError: ConnectClosedError(host.example.net)\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

The last lines of netconf traceoptions show the following when using Ansible and hitting the error:

```
Jun  7 19:09:06 [40254] Outgoing: <ok/>
Jun  7 19:09:06 [40254] Outgoing: </load-configuration-results>
Jun  7 19:09:06 [40254] Outgoing: </rpc-reply>
Jun  7 19:09:06 [40254] Outgoing: ]]>]]>
Jun  7 19:09:06 [40254] Incoming: >
Jun  7 19:09:06 [40254] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:189b3656-f83b-4ded-bcca-010450ea5017"><get-configuration compare="rollback" rollback="0" format="text"/></nc:rpc>]]>]]>
Jun  7 19:09:06 [40254] Outgoing: <!-- netconf error: syntax error, expecting &lt;rpc&gt; -->
Jun  7 19:09:07 [40254] Outgoing: <ok/>
Jun  7 19:09:07 [40254] Outgoing: <!-- session end at 2017-06-07 19:09:07 UTC -->
```

As others have mentioned, a slight change in the contents of the config file avoids the error. 

Also, I ran a quick py-ez script, using the same config file (XML), and I get no errors:

```
$ python test_netconf.py host.example.net configs/host.example.net.d/config.xml
Connecting to host.example.net
Taking lock
Loading file configs/host.example.net.d/config.xml
No diffs
Unlocking
Closing connection
```

This particular example is on:

```
Model: srx240h
JUNOS Software Release [12.1X46-D35.1]
```

But I also saw it happen on:

```
Model: qfx3500s
Junos: 14.1X53-D35.3
```

I'm running ansible 2.0.2.0, junos-eznc==2.1.3 and my version of the modules is:

```
$ cat ~/ansible-junos-stdlib/version.py
VERSION = "1.4.2"
DATE = "2017-April-24"
```

I would really appreciate any help with this. I'm happy to provide more details as needed.

**Comment by stacywsmith** [comment] 2017-06-07 20:18
@cvicente Your NETCONF traceoptions and the Junos versions where you've encountered this problem do confirm that it is the same Junos issue that others have encountered. The solution is to upgrade to a Junos version which has been fixed.

A short-term workaround is to add 5 spaces to any configuration file where you encounter this problem, and then repeat the config load.

**Comment by stacywsmith** [comment] 2017-06-07 21:04
It appears that all of the cases which have been reported under this issue are the same Junos bug. Therefore, I'm closing this issue. If anyone else sees this issue, please re-open and post the output of your NETCONF traceoptions when encountering this issue.

**Closed by stacywsmith** 2017-06-07 21:04 UTC

**Comment by cvicente** [comment] 2018-02-01 14:10
@stacywsmith do you by chance have the PR number for this bug? We are exploring upgrades and want to make sure that we pick exact versions where this bug is fixed. Thanks.

**Comment by stacywsmith** [comment] 2018-02-01 14:59
@vnitinv Can you work with @cvicente to identify the PR and fixed versions?

@cvicente I am no longer a Juniper employee so I don't have access to the PR database.

**Comment by jimealbe** [comment] 2021-01-16 00:31
@vnitinv where you able to find the PR about this issue? can you share that one pls?

**Comment by vnitinv** [comment] 2021-01-28 07:26
@jimealbe I dont have permission to PR DB as now I am into a different team/role. Will check with my engineering team and get back to you.
