### ISSUE TITLE
Update SRX5400 Cluster ISSU

### ISSUE THREAD

**Issue by infectedgti** [Juniper/ansible-junos-stdlib#254] opened 2017-08-17 15:32 UTC
Hi,

I'm trying to update SRX5400 in cluster using ISSU.
I've got this error : 

`TASK [Update JunOS for SRX5400] **************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: [Aug 17 17:06:23]: 'reboot' keyword must be specified. Aborting ISSU)
fatal: [FW-C012-1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_FyFqCm/ansible_module_junos_install_os.py\", line 317, in <module>\n    main()\n  File \"/tmp/ansible_FyFqCm/ansible_module_junos_install_os.py\", line 302, in main\n    results = junos_install_os(module, dev)\n  File \"/tmp/ansible_FyFqCm/ansible_module_junos_install_os.py\", line 230, in junos_install_os\n    ok = sw.install(package, **sw_args)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py\", line 833, in install\n    dev_timeout=timeout, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py\", line 254, in pkgaddISSU\n    package_name=remote_package, **kvargs)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py\", line 342, in _exec_rpc\n    return self._junos.execute(rpc, **dec_args)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/decorators.py\", line 76, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/decorators.py\", line 23, in wrapper\n    result = function(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/device.py\", line 790, in execute\n    errs=ex)\njnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: [Aug 17 17:06:23]: 'reboot' keyword must be specified. Aborting ISSU)\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}`

SRX5400 are in version : 

root@FW-C012-1> show version
node0:
--------------------------------------------------------------------------
Hostname: FW-C012-1
Model: srx5400
Junos: 15.1X49-D75.5
JUNOS Software Release [15.1X49-D75.5]

node1:
--------------------------------------------------------------------------
Hostname: FW-C012-1
Model: srx5400
Junos: 15.1X49-D75.5
JUNOS Software Release [15.1X49-D75.5]

I want to update them in version 15.1X49-D100.

What's wrong ?

Thank you

**Comment by stacywsmith** [comment] 2017-08-17 16:01
ISSU on SRX clusters is not officially supported by by the `junos_install_os Ansible` module, or the underlying PyEZ library which does the underlying work.

That said, you MAY be able to get this to work

The issue is that this particular platform/configuration requires the `reboot` keyword to be specified. You can see this in the error message which was returned:
```
RpcError(severity: error, bad_element: None, message: [Aug 17 17:06:23]: 'reboot' keyword must be specified. Aborting ISSU)
```
This message is being returned from the device itself.

You can pass the required `reboot` keyword by setting the `reboot: True` argument in the `junos_install_os` task of your Ansible playbook. We generally recommend against passing the `reboot` argument when performing an ISSU because it may cause the `junos_install_os` task to report a false failure. This is because the complete response isn't received from the device before it begins rebooting the old master RE. This may cause the `junos_install_os` to report a false failure, and may cause you to have to modify your playbook to ignore this false failure.

**Comment by vnitinv** [comment] 2017-09-26 06:05
@infectedgti Closing this issue. You can re-open if Stacy's suggestion doesnt work for you. Thanks

**Closed by vnitinv** 2017-09-26 06:05 UTC
