### ISSUE TITLE
parser from xml to json problems..

### ISSUE THREAD

**Issue by hrv231** [Juniper/ansible-junos-stdlib#555] opened 2021-05-20 19:19 UTC
Issue Type
------

 - Bug Report

Module Name
------

juniper.device.rpc

juniper.device collection and Python libraries version

```
ansible 2.10.5
  config file = /home/user1/ansible/ansible/ansible.cfg
  configured module search path = ["/home/user1/ansible/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/ansible/ansible/library'"]
  ansible python module location = /home/user1/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user1/ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]


juniper.device         0.1.0 
```

OS / Environment
------

ex3200 and ex3400

Summary
------

Steps to reproduce
------

When I use the below playbook with formats xml, the parser creates the unit for lo0 as {} instead of unit[]

```yaml
    - name: run rpc on the remote device
      juniper.device.rpc:
        rpcs: get-config
        formats: xml
        filter: "configuration/interfaces/interface"
      register: test
```

Expected results

When I use the playbook with formats json, then the result is what we want.
```
                {
                    "name": "lo0",
                    "unit": [
                        {
                            "family": {
                                "inet": {
                                    "address": [
                                        {
                                            "name": "100.127.0.32/32"
                                        }
                                    ],
                                    "filter": {
                                        "input": {
                                            "filter-name": "RESTRICT_ACCESS"
                                        }
                                    }
                                }
                            },
                            "name": 0
                        }
                    ]
                }
```
Actual results
------

```
                {
                    "name": "lo0",
                    "unit": {
                        "family": {
                            "inet": {
                                "address": {
                                    "name": "100.127.0.32/32"
                                },
                                "filter": {
                                    "input": {
                                        "filter-name": "RESTRICT_ACCESS"
                                    }
                                }
                            }
                        },
                        "name": "0"
                    }
                }
```

For old devices like ex3200 I can't use formats json, that's why I prefer then to use formats xml for all my devices and let the parser to do its job.
Would be good if you can fix that.

Thanks.

**Comment by rahkumar651991** [comment] 2021-05-31 02:47
@hrv231 - The formats parameter results in different output for different values provided. Json, xml and text and each will provide output in different style. The different style is there as with multiple user/vendor they have there own parser written for the particular implementation. 

JSON will provide output in a dictionary like pattern while xml provides output in a etree like pattern. 

This is not a bug but the parser needs to be written according to the use-case.

**Comment by rahkumar651991** [comment] 2021-09-16 17:51
Based on the above comment, closing the issue.

**Closed by rahkumar651991** 2021-09-16 17:51 UTC
Labels: Type: Question
